### PR TITLE
Regression test for nil href bug

### LINKED ISSUE #5: "View API" links broken
There is a link on the variables pages with the label 'view API', looks broken, haven't investigated if this is broken and if it's across multiple pages or not.

### PR DESCRIPTION
**Pull request by lamorrison**
closes #5

This is a quick regression test for a bug which is already fixed. It's mostly a formality but I think it's worth including because the two properties tested here are loaded in a different way from the other Variable properties so there's a higher chance of them getting lost somehow.

### CODE REVIEW

File: spec/services/variables_fetch_service_spec.rb [hunk 1]
```diff
@@ -45,6 +45,30 @@
...
     end
+
+    it 'correctly sets the href and description attributes' do
+      # There used to be a bug where an available href value would be
+      # overwritten by nil during the .fetch call. This could also have applied
+      # to the description (since they are retrieved in the first variables_list
+      # call). This is a regression test to ensure the values aren't lost again
+      # in future if the server responses or our code change. Note that this
+      # test isn't very useful if the OpenFisca responses are mocked above.
+      # Consider running this agains the live server to debug weird server
```
Comment (JacOng17) [inline spec/services/variables_fetch_service_spec.rb]: Consider running this **against**
